Program TEST_DVRAM;

{$i d:types.pas}
{$i d:dvram.pas}

Var
     outHandle : TOutputHandle;

Begin
  ClrScr;
  OpenDirectTextMode( outHandle );

  WriteLn( 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' );
  WriteLn( 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' );
  WriteLn( 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' );
  WriteLn( 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' );

  CloseDirectTextMode( outHandle );
End.
